# Generated by Django 4.2.1 on 2023-05-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('advice', models.CharField(max_length=100)),
                ('goal', models.CharField(max_length=100)),
                ('exercise', models.CharField(max_length=100)),
            ],
        ),
    ]
