# Generated by Django 4.2.1 on 2023-05-16 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='date',
            new_name='training_date',
        ),
    ]
