# Generated by Django 4.2.1 on 2023-05-16 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_date_progress_training_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.BooleanField(default=False)),
                ('chore', models.BooleanField(default=False)),
                ('rest', models.BooleanField(default=False)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.progress')),
            ],
        ),
    ]
