# Generated by Django 4.2.1 on 2023-05-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='chore',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='rest',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='school',
            field=models.CharField(max_length=100),
        ),
    ]
